CREATE DATABASE VINCULACRM;

USE VINCULACRM;

CREATE TABLE USER(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(120) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    TYPE TINYINT DEFAULT 1
);

CREATE TABLE EMPLOYE(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(120) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    ID_USER INT NOT NULL,
    FOREIGN KEY(ID_USER) REFERENCES USER(ID)
);

CREATE TABLE CLIENT(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(120),
    TEL VARCHAR(50),
    CELL VARCHAR(50),
    AGE INT(10),
    ID_EMPLOYE INT NOT NULL,
    FOREIGN KEY(ID_EMPLOYE) REFERENCES EMPLOYE(ID)
);

USE VINCULACRM;

SELECT * FROM USER;